theme = "onedark"

[editor]
line-number = "relative"
mouse = true
cursorline = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false